# Generated by Django 3.2.8 on 2021-12-12 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('milk_id', models.AutoField(primary_key=True, serialize=False)),
                ('milk_name', models.CharField(default='', max_length=100)),
                ('milk_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('tea_id', models.AutoField(primary_key=True, serialize=False)),
                ('tea_name', models.CharField(default='', max_length=100)),
                ('tea_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('temp_id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('topping_id', models.AutoField(primary_key=True, serialize=False)),
                ('topping_name', models.CharField(default='', max_length=100)),
                ('topping_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_flavor', models.CharField(max_length=100, null=True)),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('menu_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=100, null=True)),
                ('menu_sugar', models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], null=True)),
                ('milk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.milk')),
                ('tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tea')),
                ('temperature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.temperature')),
                ('topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drink_id', models.AutoField(primary_key=True, serialize=False)),
                ('drink_flavor', models.CharField(max_length=100, null=True)),
                ('drink_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('drink_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=100, null=True)),
                ('drink_sugar', models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], null=True)),
                ('milk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.milk')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tea')),
                ('temperature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.temperature')),
                ('topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topping')),
            ],
        ),
    ]
