# Generated by Django 3.2.8 on 2021-10-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('drink_id', models.IntegerField(primary_key=True, serialize=False)),
                ('drink_name', models.CharField(max_length=200)),
                ('drink_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('drink_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=200)),
                ('drink_sugar', models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)])),
            ],
        ),
    ]
