# Generated by Django 3.2.8 on 2021-10-31 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('flavor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flavor_name', models.CharField(default='', max_length=100)),
                ('flavor_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('milk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('milk_name', models.CharField(default='', max_length=100)),
                ('milk_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('tea_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tea_name', models.CharField(default='', max_length=100)),
                ('tea_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('temp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('temp_name', models.CharField(default='', max_length=100)),
                ('temp_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('topping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topping_name', models.CharField(default='', max_length=100)),
                ('topping_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=100),
        ),
        migrations.AddField(
            model_name='drink',
            name='flavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.flavor'),
        ),
        migrations.AddField(
            model_name='drink',
            name='milk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.milk'),
        ),
        migrations.AddField(
            model_name='drink',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
        migrations.AddField(
            model_name='drink',
            name='tea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tea'),
        ),
        migrations.AddField(
            model_name='drink',
            name='temp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.temperature'),
        ),
        migrations.AddField(
            model_name='drink',
            name='topping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topping'),
        ),
    ]
