# Generated by Django 3.1.4 on 2021-11-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211031_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='temp',
            new_name='temperature',
        ),
    ]
