# Generated by Django 3.1.4 on 2021-11-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211102_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='temp_price',
        ),
    ]
