# Generated by Django 3.1.4 on 2021-12-11 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_temperature_temp_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='drink_name',
            new_name='drink_flavor',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='flavor',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
    ]
