# Generated by Django 3.1.4 on 2021-12-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_temperature_temp_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='flavor',
        ),
    ]
