# Generated by Django 3.2.8 on 2021-12-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211211_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='drink_flavor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_sugar',
            field=models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], null=True),
        ),
    ]
