# Generated by Django 3.2.8 on 2021-12-12 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211211_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_flavor', models.CharField(max_length=100, null=True)),
                ('menu_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('menu_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=100, null=True)),
                ('menu_sugar', models.IntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], null=True)),
                ('milk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.milk')),
                ('tea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tea')),
                ('temperature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.temperature')),
                ('topping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.topping')),
            ],
        ),
    ]
